version: '3'

services:
  contactserviceapi:
    image: contactbook/contactserviceapi:${TAG:-latest}
    #environment:
    #  - OMS_MQ_USERNAME=oms
    #  - OMS_MQ_PASSWORD=password
    #  - OMS_MQ_SERVER=ordermanagementsystemmq
    build:
      context: .
      dockerfile: src/Services/ContactService/ContactService.API/Dockerfile
    ports:
      - "5103:80"
    depends_on:
      - rabbitmq
    #  - sqldata
      

  #sqldata:
  #  image: microsoft/mssql-server-linux:2017-latest
  #  environment:
  #    SA_PASSWORD: "Qweasd123"
  #    ACCEPT_EULA: "Y"
  #  ports:
  #    - "5433:1433"

  #webspa:
  #  image: contactbook/webspa:${TAG:-latest}
  #  build:
  #    context: .
  #    dockerfile: WebSPA/Dockerfile
  #  ports:
  #    - "5102:80"

  orderserviceapi:
    image: contactbook/orderserviceapi:${TAG:-latest}
    #environment:
    #  - OMS_MQ_USERNAME=oms
    #  - OMS_MQ_PASSWORD=password
    #  - OMS_MQ_SERVER=ordermanagementsystemmq
    build:
      context: .
      dockerfile: src/Services/OrderService/OrderService.API/Dockerfile
    ports:
      - "5104:80"
    depends_on:
      - rabbitmq
    #  - sqldata
         

  #rabbitmq:
  #  image: rabbitmq:3-management-alpine
  #  container_name: ordermanagementsystemmq
  #  hostname: ordermanagementsystemmq
  #  ports:
  #      - 15672:15672
  #      - 5671:5671
  #      - 5672:5672
  #  environment:
  #      - RABBITMQ_DEFAULT_USER=oms
  #      - RABBITMQ_DEFAULT_PASS=password

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 15672:15672
      - 5671:5671
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest