version: '3'

services:
  contactservice.api:
    environment:
     - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5101:80"

  sql.data:
      environment:
        - SA_PASSWORD=Qweasd123#
        - ACCEPT_EULA=Y
      ports:
        - "5433:1433"